SproostApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls import handler400, handler500, handler404
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views




from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from dj_rest_auth.registration.views import RegisterView
from dj_rest_auth.views import LoginView, LogoutView, UserDetailsView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from django.urls import path

# handler400 = 'accounts.views.custom_bad_request'
# handler404 = 'accounts.views.custom_bad_request'
# handler500 = 'accounts.views.custom_server_error'

urlpatterns = [

    # path('dj-rest-auth/', include('dj_rest_auth.urls')),
    # path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # path('dj-rest-auth/social/', include('dj_rest_auth.social.urls')),  

    path('admin/', admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="api-schema"), name="api-docs"),
    path('api/auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    
    # path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api/auth/', include('dj_rest_auth.urls')),
    # path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
    # path("register/", RegisterView.as_view(), name="rest_register"),
    # path("login/", LoginView.as_view(), name="rest_login"),
    # path("logout/", LogoutView.as_view(), name="rest_logout"),
    # path("user/", UserDetailsView.as_view(), name="rest_user_details"),

    # path('admin/', admin.site.urls),
    path('user-admin/', include('admins.urls', namespace='admins')),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profile')),
    path('quotes/', include('quotes.urls', namespace='quotes')),
    path('property/', include('property.urls', namespace='property')),


    # Django's built-in password reset views
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/urls.py
from django.urls import path
from . import views


app_name = 'admins'
urlpatterns = [
    path('dashboard/', views.AdminDashboardAPIView.as_view(), name="dashboard"),
    path('contractors/', views.ContractorsListAPIView.as_view(), name="contractors"),
    path('home-owners/', views.HomeOwnersListAPIView.as_view(), name="homeowners"),
    path('agents/', views.AgentsListAPIView.as_view(), name="agents"),
    path('project-requests/', views.ProjectRequestListAPIView.as_view(), name="project-requests"),
    path('project-requests/<int:id>/', views.ProjectRequestDetailAPIView.as_view(), name="project-requests"),
    path('active-projects/', views.ActiveProjectListAPIView.as_view(), name="active-projects"),
    # path('change-quote-status/<int:pk>/', views.ChangeQuoteStatusAPIView.as_view(), name="change-quote"),
    path('contractors/update/<int:pk>/', views.UpdateContractorAPIView.as_view(), name="update-contractor"),
    path('home-owner/update/<int:pk>/', views.UpdateHomeOwnerAPIView.as_view(), name="update-home_owner"),
    path('agent/update/<int:pk>/', views.UpdateAgentAPIView.as_view(), name="update-agent"),
  
]

chat/urls.py
from django.urls import path, include

from . import views 





urlpatterns = [

    path('cloudinary-signature/', views.CloudinarySignatureView.as_view(), name='cloudinary-signature'),
    path('delete_media/<str:public_id>/', views.DeleteMediaView.as_view(), name='delete_media'),
    path('live_admin_user_search/', views.AdminSearchUserAPIView.as_view(), name="live_admin_user_search"),
    path('chat/create_room/', views.CreateRoomAPIView.as_view(), name='create_room'),
    path("search_messages/", views.SearchMessagesView.as_view(), name="search_messages"),
    path('rooms/<int:room_id>/add-members/', views.AddMembersAPIView.as_view(), name='add-members'),
    path('rooms/<int:room_id>/leave/', views.LeaveRoomAPIView.as_view(), name='leave-room'),
    path('rooms/<int:room_id>/delete/', views.DeleteRoomAPIView.as_view(), name='delete-room'),

]

templates/user_admin/dashboard.html
{% extends "user_admin/base.html" %} 
{% load static %} 
{% load form_tags %}
{% block navbar %} 
    {% include "user_admin/navbar.html" %} 
{% endblock navbar %} 
{% block content %}
<main class="w-full px-[1rem] md:px-[4rem] flex flex-col gap-8 my-8">
    <h2 class="text-xl text-gray-900 font-semibold">Dashboard</h2>
    <div class="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {% for stat in overall_stats %}
        <div class="w-full p-4 bg-white border border-neutral-150 rounded-md shadow-sm">
            <div class="w-full flex flex-col gap-4">
                <div class="w-full flex items-center justify-between">
                    <h3 class="text-gray-600 font-medium">{{stat.title}}</h3>
                    {% comment %} <span class="">
                        <img src="{% static 'svgs/more-vertical.svg' %}" alt="" class="" />
                    </span> {% endcomment %}
                </div>

                <div class="w-full flex items-center justify-between">
                    <h3 class="text-gray-900 text-2xl font-semibold">{{stat.project_counts}}</h3>
                </div>
                <div class="flex justify-end border-t border-neutral-150 items-center p-2">
                    <a href="{{stat.link}}" class="text-primary font-medium ">{{stat.action}}</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

    <!-- grid cards -->
    <div class="w-full grid grid-cols-1 md:grid-cols-2 gap-4">
        <!-- column 1 -->
        <div class="rounded-lg w-full border border-neutral-150 p-4">
            <!-- header -->
            <div class="w-full flex items-center justify-between border-b border-neutral-150 pb-4">
                <h3 class="text-gray-900 font-semibold">Recent Home Owners</h3>
                <a href="{% url "admins:homeowners" %}" class="text-primary bg-toneLightGreen text-center p-2 px-4 rounded-md"> See all </a>
            </div>
            <!-- table search result -->
            <div class="w-full my-2">
                <table class="w-full">
                    <thead class="h-10 bg-gray-200 bg-opacity-80">
                        <tr class="text-gray-600 text-xs font-medium">
                            <th class="w-1/4 text-start p-4">Name</th>
                            <th class="w-1/4 text-start p-4">Contact</th>
                            <th class="w-1/4 text-start p-4">Recent Project</th>
                            <th class="w-1/4 text-start p-4">Quotation Status</th>
                        </tr>
                    </thead>
                    <tbody class="p-4">
                        {% for home_owner in recent_home_owners %}
                        <tr class="border-b border-neutral-100 last:border-0">
                            <td class="w-1/4 p-4">
                                <a href="{% url 'admins:update_home_owner' home_owner.pk %}" class="flex gap-1 items-center">
                                    <img class = "w-4" src = {% static "svgs/edit-02.svg" %} />
                                    <div class="w-full flex items-center gap-2">
                                        <p class="text-gray-900 text-sm font-medium capitalize">{{home_owner.first_name}} {{home_owner.last_name}}</p>
                                    </div>
                                </a>
                            </td>
                            <td class="w-1/4 p-4">
                                <div class="flex flex-col gap-1">
                                    <span class="text-gray-500 text-sm">{{home_owner.phone_number}}</span>
                                    <span class="text-gray-500 text-sm">{{home_owner.email}}</span>
                                </div>
                            </td>
                            <td class="w-1/4 p-4">
                                <span class=" font-semibold text-xs rounded-xl p-1 px-2 border border-neutral-150 bg-gray-50 bg-opacity-90 {% if home_owner.quote_requests.latest_quote.status|lower == 'approved' %} bg-toneLightGreen text-primary bg-opacity-70 border-primary {% elif home_owner.quote_requests.latest_quote.status|lower == 'rejected' %} bg-[#B42318] bg-opacity-50 border-red-500 text-[#B42318] {% endif %} "> 
                                    {{home_owner.quote_requests.latest_quote.title|default:"no projects"}}
                                </span>
                            </td>

                            <td class="w-1/4 p-4 ">
                                <div class="inline-flex items-center gap-2 rounded-xl p-1 px-2 border border-neutral-150">
                                    {% if home_owner.quote_requests.latest_quote.status %}
                                    <span class="w-2 h-2 bg-[#B42318] rounded-full {% if home_owner.quote_requests.latest_quote.status|lower == 'approved' %} bg-primary {% elif home_owner.quote_requests.latest_quote.status|lower == 'pending' %} bg-yellow-500 {% endif %} "></span>
                                    <span class="font-semibold text-xs capitalize"> 
                                        {{home_owner.quote_requests.latest_quote.status}}
                                    </span>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- column 2 -->
        <div class="rounded-lg w-full border border-neutral-150 p-4">
            <!-- header -->
            <div class="w-full flex items-center justify-between border-b border-neutral-150 pb-4">
                <h3 class="text-gray-900 font-semibold">Recent Agents</h3>
                <a href="{% url 'admins:agents' %}" class="text-primary bg-toneLightGreen text-center p-2 px-4 rounded-md"> See all </a>
            </div>
            <!-- table search result -->
            <div class="w-full my-2">
                <table class="w-full">
                    <thead class="h-10 bg-gray-200 bg-opacity-80">
                        <tr class="text-gray-600 text-xs font-medium">
                            <th class="w-1/4 text-start p-4">Name</th>
                            <th class="w-1/4 text-start p-4">Contact</th>
                            <th class="w-1/4 text-start p-4">Total Projects</th>
                        </tr>
                    </thead>
                    <tbody class="p-4">
                        {% for agent in recent_agents %}
                        <tr class="border-b border-neutral-100 last:border-0">
                            <td class="w-1/4 p-4">
                                <a href = {% url 'admins:update_agent' agent.pk %} class="flex gap-1 items-center text-gray-900 text-sm font-medium capitalize">
                                    <img class = "w-4" src = {% static "svgs/edit-02.svg" %} />
                                    {{agent.first_name}} {{agent.last_name}}
                                </a>
                            </td>
                            <td class="w-1/4 p-4">
                                <div class="flex flex-col gap-1">
                                    <span class="text-gray-500 text-sm">{{agent.phone_number}}</span>
                                    <span class="text-gray-500 text-sm">{{agent.email}}</span>
                                </div>
                            </td>
                            <td class="w-1/4 p-4 ">
                                <div class="inline-flex items-center rounded-full bg-gray-50 p-2 border border-neutral-150">
                                    <span class="font-semibold text-xs capitalize"> 
                                        {{agent.total_projects}}
                                    </span>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- column 3 -->
        <div class="rounded-lg w-full border border-neutral-150 p-4">
            <!-- header -->
            <div class="w-full flex items-center justify-between border-b border-neutral-150 pb-4">
                <h3 class="text-gray-900 font-semibold">Recent Contractors</h3>
                <a href="{% url "admins:contractors" %}" class="text-primary bg-toneLightGreen text-center p-2 px-4 rounded-md"> See all </a>
            </div>
            <!-- table search result -->
            <div class="w-full my-2">
                <table class="w-full">
                    <thead class="h-10 bg-gray-200 bg-opacity-80">
                        <tr class="text-gray-600 text-xs font-medium">
                            <th class="w-1/4 text-start p-4">Name</th>
                            <th class="w-1/4 text-start p-4">Contact</th>
                        </tr>
                    </thead>
                    <tbody class="p-4">
                        {% for contractor in recent_contractors %}
                        <tr class="border-b border-neutral-100 last:border-0">
                            <td class="w-1/4 p-4">
                                <a href = {% url 'admins:update_contractor' contractor.pk %} class="text-gray-900 text-sm font-medium capitalize flex gap-1 items-center">
                                    <img class = "w-4" src = {% static "svgs/edit-02.svg" %} />
                                    {{contractor.contractor_profile.company_name}}
                                </a>
                            </td>
                            <td class="w-1/4 p-4">
                                <div class="flex flex-col gap-1">
                                    <span class="text-gray-500 text-sm">{{contractor.phone_number}}</span>
                                    <span class="text-gray-500 text-sm">{{contractor.email}}</span>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- column 4 -->
        <div class="rounded-lg w-full border border-neutral-150 p-4">
            <!-- header -->
            <div class="w-full flex items-center justify-between border-b border-neutral-150 pb-4">
                <h3 class="text-gray-900 font-semibold">Recent Project Request</h3>
                <a href="{% url "admins:project-requests" %}" class="text-primary bg-toneLightGreen text-center p-2 px-4 rounded-md"> See all </a>
            </div>
            <div class="flex mt-6 overflow-x-scroll hide-scroll">
                <div class="flex gap-4 items-center">
                    {% for quote in recent_quote_requests %}
                    <div class="w-full flex flex-col gap-4 p-4 border text-xs border-neutral-150 rounded-md w-max">
                        <div class="w-full flex items-center justify-between">
                            <div class="text-xs flex flex-col gap-2">
                                <span class="text-gray-500 font-medium">Project Name</span>
                                <h3 class="text-gray-600 font-semibold">{{quote.title}}</h3>
                            </div>
                            {% comment %} <span class="">
                                <img src="{% static 'svgs/more-vertical.svg' %}" alt="" class="" />
                            </span> {% endcomment %}
                        </div>
                        <div class="flex items-start gap-8">
                            <div class="">
                                <span class="text-gray-500 font-medium">Home Owner</span>
                                <div class="flex items-center gap-4 mt-2">
                                    <span class="text-gray-900 font-medium">{{quote.user.first_name}} {{quote.user.last_name}}</span>
                                    <img src="{% static 'svgs/chat-msg.svg' %}" alt="" />
                                </div>
                            </div>
                            <div class="text-xs flex flex-col gap-2">
                                <span class="text-gray-500 font-medium">Created Date</span>
                                <h3 class="text-gray-600 font-semibold mt-2">{{quote.upload_date|date:"F j, Y"}}</h3>
                            </div>
                        </div>
                        <div class="flex items-start gap-8">
                            <div class="text-xs flex flex-col gap-2">
                                <span class="text-gray-500 font-medium">Location</span>
                                <h3 class="text-gray-600 font-semibold mt-2">{{quote.property_address}}</h3>
                            </div>
                            <div class="text-xs flex flex-col gap-2">
                                <span class="text-gray-500 font-medium">Quotation Status</span>
                                <div id = "QuoteStatusContainer{{quote.pk}}" class = "p-1 px-2 bg-gray-200 text-[10px] bg-opacity-50 w-fit  border border-neutral-150 rounded-xl">
                                    {% include "user_admin/partials/QuoteStatusForm.html" %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/user_admin/login.html
{% extends "admin/base.html" %} {% load static %} {% block authContent %}

<div class="w-full flex items-center justify-center h-screen">
    <div class="w-1/2 2xl:w-[40%] mx-auto flex flex-col gap-8 items-center justify-center">
        <img src="{% static 'svgs/sproost-plus.svg' %}" alt="" class="" />
        <div class="flex flex-col items-center justify-center">
            <h3 class="text-gray-900 font-semibold text-xl">Log in to your account</h3>
            <p class="text-gray-600 text-base">Welcome back! Please enter your details.</p>
        </div>
        <form action="" method="post" class="flex flex-col gap-4 w-full">
            {% csrf_token %}
            <div class="flex flex-col gap-2 w-full">
                <label for="email" class="text-gray-600 text-sm">Email</label>
                <input type="email" name="email" id="email" placeholder="Enter your email" class="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-gray-500" required />
            </div>
            <div class="flex flex-col gap-2 w-full">
                <label for="password" class="text-gray-600 text-sm">Password</label>
                <input type="password" name="password" id="password" class="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-gray-500" required />
            </div>
            <div class="flex items-center justify-between gap-2 w-full">
                <label for="remember" class="flex items-center">
          <input type="checkbox" id="remember" name="remember" class="mr-2" />
          <span class="text-gray-600 text-sm">Remember for 30 days</span>
        </label>
                <a href="#" class="text-primary font-semibold text-sm">Forgot password?</a>
            </div>

            <div class="flex flex-col gap-4 mt-5 w-full">
                <button type="submit" class="w-full p-3 shadow-sm bg-primary text-white rounded-md font-semibold focus:outline-none focus:bg-primary">Sign in</button>
            </div>

        </form>
    </div>
</div>
{% endblock authContent %}

templates/user_admin/navbar.html
{% load static %}
<nav class="w-full px-[1rem] md:px-[4rem] py-2 border-b border-neutral-150 text-gray-700 flex items-center justify-between">
    <a href={% url 'admins:dashboard' %}> <img src="{% static 'svgs/sproost-plus.svg' %}" alt="" class=""> </a>
    {% with url_name=request.resolver_match.url_name %}
        <ul class="inline-flex items-center gap-6">
            <li class="text-gray-700 font-semibold cursor-pointer {% if url_name == 'dashboard' %} bg-toneLightGreen text-primary bg-opacity-80 p-2 px-4 w-fit rounded-md {% endif %}">
                <a href="{% url 'admins:dashboard' %}" class="">Dashboard</a>
            </li>
            <li class="text-gray-700 font-semibold cursor-pointer {% if url_name == 'project-requests' %} bg-toneLightGreen text-primary bg-opacity-80 p-2 px-4 w-fit rounded-md {% endif %}">
                <a href="{% url 'admins:project-requests' %}" class="">Project Requests</a>
            </li>
            <li class="text-gray-700 font-semibold cursor-pointer {% if url_name == 'active-projects' %} bg-toneLightGreen text-primary bg-opacity-80 p-2 px-4 w-fit rounded-md {% endif %}">
                <a href="{% url "admins:active-projects" %}" class="">Active Request</a>
            </li>
            <li class="text-gray-700 font-semibold cursor-pointer {% if url_name == 'homeowners' %} bg-toneLightGreen text-primary bg-opacity-80 p-2 px-4 w-fit rounded-md {% endif %}">
                <a href="{% url "admins:homeowners" %}" class="">Home Owners</a>
            </li>
            <li class="text-gray-700 font-semibold cursor-pointer {% if url_name == 'contractors' %} bg-toneLightGreen text-primary bg-opacity-80 p-2 px-4 w-fit rounded-md {% endif %}">
                <a href="{% url 'admins:contractors' %}" class="">Contractors</a>
            </li>
        </ul>
    {% endwith %}
    <form action="{% url 'account_logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="flex gap-2 items-center rounded-md text-black bg-white border border-gray-300 p-2 cursor-pointer">Logout <img src = "{% static 'svgs/logout.svg' %}" class = "w-4 h-4" /></button>
    </form>
</nav>

templates/user_admin/project_request.html
{% extends "user_admin/base.html" %} {% load static %} {% block navbar %} {% include "user_admin/navbar.html" %} {% endblock navbar %} {% block content %}
<main class="w-full px-[1rem] md:px-[4rem] flex flex-col gap-8 my-8">
    <div class="">
        <div class="mb-4">
            <h1 class="text-2xl font-semibold text-gray-700">Project Request</h1>
        </div>
        <div class="w-full flex items-center justify-between">
            <div class="w-1/3 group border border-gray-300 rounded-md flex items-center gap-2 p-2 mt-1">
                <img src="{% static 'svgs/search.svg' %}" alt="" class="w-[20px] h-[20px] object-contain" />
                <input type="text" name="search" id="search" placeholder="Search" class="w-full h-full outline-none group-focus:outline-none mt-1 focus-visible:border-none border-none" />
            </div>
            {% comment %} <div class="group border border-gray-300 rounded-md flex items-center justify-center gap-2 p-2 mt-1">
                <img src="{% static 'svgs/Filterlines.svg' %}" alt="" class="w-[20px] h-[20px] object-contain" />
                <span class="text-gray-700 font-semibold text-sm">Filters</span>
            </div> {% endcomment %}
        </div>
    </div>
    <div class="">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-6">
            {% for quote in page_obj %}
            <a href="{% url 'admins:project-requests' quote.id %}" class="hover:shadow-md w-full flex flex-col gap-4 p-4 border text-xs border-neutral-150 rounded-md shadow-sm">
                <div class="w-full flex items-center justify-between">
                    <div class="text-xs flex flex-col gap-2">
                        <span class="text-gray-500 font-medium">Project Name</span>
                        <h3 class="text-gray-600 font-semibold">{{quote.title}}</h3>
                    </div>
                    {% comment %} <span class="">
                        <img src="{% static 'svgs/more-vertical.svg' %}" alt="" class="" />
                    </span> {% endcomment %}
                </div>
                <div class="flex items-start gap-12 w-full">
                    <div class="">
                        <span class="text-gray-500 font-medium">Home Owner</span>
                        <div class="flex items-center gap-4 mt-2">
<!--                            <img src="{{project.user.image.url}}" alt="" class="w-8 h-8 object-contain" />-->
                            <span class="text-gray-900 font-medium">{{quote.user.first_name}} {{quote.user.last_name}}</span>
                            <img src="{% static 'svgs/chat-msg.svg' %}" alt="" />
                        </div>
                    </div>
                    <div class="text-xs flex flex-col gap-2">
                        <span class="text-gray-500 font-medium">Created Date</span>
                        <h3 class="text-gray-600 font-semibold mt-2">{{quote.upload_date}}</h3>
                    </div>
                </div>
                <div class="flex items-start gap-14 w-full">
                    <div class="text-xs flex flex-col gap-2">
                        <span class="text-gray-500 font-medium">Location</span>
                        <h3 class="text-gray-600 font-semibold mt-2">{{quote.property_address}}</h3>
                    </div>
                    <div class="text-xs flex flex-col gap-2">
                        <span class="text-gray-500 font-medium">Quotation Status</span>
                        <div id = "QuoteStatusContainer{{quote.pk}}" class = "quoteContainer p-1 px-2 bg-gray-200 text-[10px] bg-opacity-50 w-fit  border border-neutral-150 rounded-xl">
                            {% include "user_admin/partials/QuoteStatusForm.html" %}
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        <div class="flex items-center justify-between p-4 border-t mt-4 border-neutral-150">
             {% if page_obj.has_previous %}

                <button class="inline-flex items-center justify-center border border-neutral-150 rounded-md p-2 outline-none shadow-sm">
                    <a href="?page={{ page_obj.previous_page_number }}"><img src="{%  static 'svgs/arrow-left.svg' %}" alt="" class="" /></a>

                </button>
            {% endif %}

            <span class="text-gray-700  text-sm font-medium">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_next %}
                <button class="inline-flex items-center justify-center border border-neutral-150 rounded-md p-2 outline-none shadow-sm">
                    <a href="?page={{ page_obj.next_page_number }}"><"{%  static 'svgs/arrow-right.svg' %}" alt="" class="" /></a>
                </button>
            {% endif %}

        </div>
    </div>
</main>
{% endblock %}
{% block extraScripts %}
    <script src = "{% static "js/user_admin/project_request.js" %}"></script>
{% endblock extraScripts %}

templates/user_admin/update_agent.html
{% extends "user_admin/base.html" %} 
{% load static %} 
{% load form_tags %}
{% block navbar %} 
    {% include "user_admin/navbar.html" %} 
{% endblock navbar %}
{% block content %}
<main class="w-full  flex flex-col gap-8 my-8">
    <div class = "text-xl font-semibold mt-3 text-center">Update Agent</div>
    <div class = "w-[95%] lg:w-[70%] xl:w-[60%] m-auto">
        {{form.media}}
        <form  class="w-full mt-4 flex flex-col gap-4" method="POST">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="bg-red-400 rounded-md text-center border border-red-700">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="w-full">
                <label for="email" class="text-gray-700 font-medium text-sm">Email</label>
                {{ form.email|addattrs:"class=w-full p-2 text-gray-500 border border-gray-300 rounded-md focus:outline-none mt-1 focus:border-gray-500"}}
                {% if form.email.errors %}
                    <div class = "w-full py-1 rounded text-red-500">
                        {{form.email.errors}}
                    </div>
                {% endif %}
            </div>
            <div class="w-full">
                <label for="phone_number" class="text-gray-700 font-medium text-sm">Phone number</label>
                <!-- Render phone_number field using Django template tag -->
                <div class = "flex">
                    {{form.phone_number|addattrs:"class=w-full p-2 text-gray-500 border border-gray-300 rounded-md focus:outline-none mt-1 focus:border-gray-500,placeholder=Phone number"}}
                    {% if form.phone_number.errors %}
                        <div class = "w-full py-1 rounded text-red-500">
                            {{form.phone_number.errors}}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="w-full">
                <label for="address" class="text-gray-700 font-medium text-sm">Registration ID</label>
                {{form.registration_ID|addattrs:"class=w-full p-2 text-gray-500 border border-gray-300 rounded-md focus:outline-none mt-1 focus:border-gray-500,placeholder=Registration ID"}}
                {% if form.registration_ID.errors %}
                    <div class = "w-full py-1 rounded text-red-500">
                        {{form.registration_ID.errors}}
                    </div>
                {% endif %}
            </div>
            <div class="w-full">
                <label for="address" class="text-gray-700 font-medium text-sm">Address</label>
                {{form.address}}
                {% if form.address.errors %}
                    <div class = "w-full py-1 rounded text-red-500">
                        {{form.address.errors}}
                    </div>
                {% endif %}
            </div>
            <div class="flex w-full gap-2 border-t border-neutral-150 pt-5">
                <button type="submit" class="flex items-center w-fit justify-center px-4 py-2 rounded-lg bg-primary text-white border border-gray-150 shadow-sm font-semibold">
                    Save 
                </button>
                <a href = "{% url 'admins:agents' %}" class="flex items-center w-fit justify-center px-4 py-2 rounded-lg border border-gray-800 text-gray-700 shadow-sm font-semibold">
                    back 
                </a>
            </div>
        </form>
    </div>
</main>
{% endblock %} {% block extraScripts %}
<script src="{% static 'js/requestDetails.js' %}"></script>
{% endblock extraScripts %}