SproostApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls import handler400, handler500, handler404
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views




from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from dj_rest_auth.registration.views import RegisterView
from dj_rest_auth.views import LoginView, LogoutView, UserDetailsView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from django.urls import path

# handler400 = 'accounts.views.custom_bad_request'
# handler404 = 'accounts.views.custom_bad_request'
# handler500 = 'accounts.views.custom_server_error'

urlpatterns = [

    # path('dj-rest-auth/', include('dj_rest_auth.urls')),
    # path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # path('dj-rest-auth/social/', include('dj_rest_auth.social.urls')),  

    path('admin/', admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="api-schema"), name="api-docs"),
    path('api/auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    
    # path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api/auth/', include('dj_rest_auth.urls')),
    # path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
    # path("register/", RegisterView.as_view(), name="rest_register"),
    # path("login/", LoginView.as_view(), name="rest_login"),
    # path("logout/", LogoutView.as_view(), name="rest_logout"),
    # path("user/", UserDetailsView.as_view(), name="rest_user_details"),

    # path('admin/', admin.site.urls),
    path('user-admin/', include('admins.urls', namespace='admins')),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profile')),
    path('quotes/', include('quotes.urls', namespace='quotes')),
    path('property/', include('property.urls', namespace='property')),


    # Django's built-in password reset views
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, include

from . import views 





urlpatterns = [

    path('cloudinary-signature/', views.CloudinarySignatureView.as_view(), name='cloudinary-signature'),
    path('delete_media/<str:public_id>/', views.DeleteMediaView.as_view(), name='delete_media'),
    path('live_admin_user_search/', views.AdminSearchUserAPIView.as_view(), name="live_admin_user_search"),
    path('chat/create_room/', views.CreateRoomAPIView.as_view(), name='create_room'),
    path("search_messages/", views.SearchMessagesView.as_view(), name="search_messages"),
    path('rooms/<int:room_id>/add-members/', views.AddMembersAPIView.as_view(), name='add-members'),
    path('rooms/<int:room_id>/leave/', views.LeaveRoomAPIView.as_view(), name='leave-room'),
    path('rooms/<int:room_id>/delete/', views.DeleteRoomAPIView.as_view(), name='delete-room'),

]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    # path('homeview-bypk/<int:pk>/', views.HomeViewByPkAPIView.as_view(), name='homeview-bypk'),
    # path('assign-agent/', views.AssignAgentAPIView.as_view(), name="assign-agent"),
    # path('assigned-projects/', views.AssignedProjectsView.as_view(), name="assigned-projects"),
    # path('home-owners/<str:name>/', views.HomeOwnerWithSlugNameView.as_view(), name="home_owner_with_slug_name"),
    # path('menu/', views.MenuList, name="menu"),
    # path('quotes-summary/', views.QuotationReturn, name="quotes-summary"),
]

quotes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import QuotesAPIView,ListQuotesForPropertyView

app_name = 'quotes'

# router = DefaultRouter()
# router.register(r'projects', ProjectViewSet)

urlpatterns = [
    path('request-quotes/', QuotesAPIView.as_view(), name="request-quotes"),
    path('view_individual_quote/<int:property_id>/', ListQuotesForPropertyView.as_view(), name="view_individual_quote"),
    # path('request-quotes/<str:name>', Quotes.as_view(), name="request-quotes"),
    # path('api/', include(router.urls)),


]

templates/user/agent_message.html
{% extends "user/base.html" %} 
{% load static %} 
{% block content %}


<div>
    <!-- company logo -->
    <div class="flex w-full items-center justify-center mt-8">
        <img src="/static/svgs/sproost-name.svg" alt="" class="w-[8rem]">
    </div>
    
    <!-- go back arrow -->
    <div class="w-full p-4 flex items-center gap-8 border-b border-neutral-150">
        <img onclick="goBack()" src="{% static 'svgs/chevron-left.svg' %}" alt="" class="cursor-pointer" />
        <h3 class="text-xl text-gray-900 font-medium">Messages</h3>
    </div>

    <div class="">
        <div class="cursor-pointer">
            <div class="flex items-center justify-between pt-3 pl-4 pr-12">
                <div class="flex gap-4 items-center">
                    <img src="/static/images/dpavatar.jpg" alt="" class="w-[50px] h-[50px] rounded-full">
                    <div>
                        <p class="text-gray-900 font-medium">Agent 1</p>
                        <p class="text-gray-500 text-sm">Agent 1</p>
                    </div>
                </div>
                <i class="fa fa-check-circle text-primary" aria-hidden="true"></i>
            </div>
            <div class="w-full border-b border-neutral-150 pt-3"></div>
        </div>
        <div class="cursor-pointer">
            <div class="flex items-center justify-between pt-3 pl-4 pr-12">
                <div class="flex gap-4 items-center">
                    <img src="/static/images/dpavatar.jpg" alt="" class="w-[50px] h-[50px] rounded-full">
                    <div>
                        <p class="text-gray-900 font-medium">Agent 1</p>
                        <p class="text-gray-500 text-sm">Agent 1</p>
                    </div>
                </div>
                <i class="fa fa-check-circle" aria-hidden="true"></i>
            </div>
            <div class="w-full border-b border-neutral-150 pt-3"></div>
        </div>
        <div class="cursor-pointer">
            <div class="flex items-center justify-between pt-3 pl-4 pr-12">
                <div class="flex gap-4 items-center">
                    <img src="/static/images/dpavatar.jpg" alt="" class="w-[50px] h-[50px] rounded-full">
                    <div>
                        <p class="text-gray-900 font-medium">Agent 1</p>
                        <p class="text-gray-500 text-sm">Agent 1</p>
                    </div>
                </div>
                <i class="fa fa-check-circle" aria-hidden="true"></i>
            </div>
            <div class="w-full border-b border-neutral-150 pt-3"></div>
        </div>
        <div class="cursor-pointer">
            <div class="flex items-center justify-between pt-3 pl-4 pr-12">
                <div class="flex gap-4 items-center">
                    <img src="/static/images/dpavatar.jpg" alt="" class="w-[50px] h-[50px] rounded-full">
                    <div>
                        <p class="text-gray-900 font-medium">Agent 1</p>
                        <p class="text-gray-500 text-sm">Agent 1</p>
                    </div>
                </div>
                <i class="fa fa-check-circle text-primary" aria-hidden="true"></i>
            </div>
            <div class="w-full border-b border-neutral-150 pt-3"></div>
        </div>
        <div class="cursor-pointer">
            <div class="flex items-center justify-between pt-3 pl-4 pr-12">
                <div class="flex gap-4 items-center">
                    <img src="/static/images/dpavatar.jpg" alt="" class="w-[50px] h-[50px] rounded-full">
                    <div>
                        <p class="text-gray-900 font-medium">Agent 1</p>
                        <p class="text-gray-500 text-sm">Agent 1</p>
                    </div>
                </div>
                <i class="fa fa-check-circle text-primary" aria-hidden="true"></i>
            </div>
            <div class="w-full border-b border-neutral-150 pt-3"></div>
        </div>
        <p class="w-full text-center text-primary cursor-pointer text-meduim mt-8">Load more</p>
    </div>


{% endblock content %} 
{% block extraScripts %}

<script>
    function goBack() {
        history.back()
    }
</script>
{% endblock extraScripts %}

templates/user/all_property.html
{% extends "user/base.html" %} {% load static %} {% block content %}
{% load form_tags %}
  <style>
    .fab {
      position: fixed;
      bottom: 80px;
      left: 50%;
      transform: translateX(-50%);
    }
  </style>

<div class="w-full h-full bg-gray-100">
    <!-- go back arrow -->
    <div class="w-full p-4 flex items-center pt-8">
        <div onclick="goBack()">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 cursor-pointer">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
            </svg>
        </div>
        <h3 class="w-full text-xl mr-[48px] text-center text-gray-900 font-medium">Property List</h3>
    </div>

     <!-- Floating Action Button (FAB) -->
  <div class="w-full flex justify-center mt-[21px] mb-4">
    <button class="inline-flex items-center w-[70%] md:w-[50%] justify-center p-3 rounded-3xl bg-black text-white border border-neutral-150 shadow-sm font-semibold">Add New Property</button>
  </div>

  <!-- Listings Count -->
  <div class="p-4">
    <p class="text-xl font-bold text-gray-800">140 listings</p>
  </div>

  <!-- Property Cards -->
  <div class="p-4 grid grid-cols-1 justify-center items-center gap-4 sm:grid-cols-2 lg:grid-cols-3 pb-[100px] sm:pb-[120px] md:pb-[140px]">
    <!-- Property Card 1 -->
    <div class="bg-white rounded-lg shadow-md overflow-hidden">
      <img src="{% static 'images/bannerAfter.png' %}" alt="Property Image" class="w-full h-40 object-cover">
      <div class="p-4">
        <h2 class="text-lg font-bold text-gray-800">Bungalow Renovation</h2>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Created Date</p>
          <p class="text-sm text-gray-600">Jan 28, 2024</p>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Project Duration</p>
          <p class="text-sm text-gray-600">3 Months</p>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Home Owner</p>
          <div class="flex items-center">
            <img src="owner-image.jpg" alt="Owner Image" class="w-6 h-6 rounded-full">
            <p class="text-sm text-gray-600 ml-2">Olivia Rhye</p>
          </div>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Home Location</p>
          <p class="text-sm text-gray-600">35st California road, off 5th New York</p>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Quotation Status</p>
          <div class="flex gap-1 items-center bg-yellow-100 rounded-full px-2 py-1">
              <div class="w-[10px] h-[10px] rounded-full bg-yellow-500 "></div>
              <div class="text-sm text-yellow-500">Pending</div>
          </div>
        </div>
        <div class="text-center">
            <button class="inline-flex items-center w-[70%] md:w-[50%] justify-center p-3 rounded-3xl bg-black text-white border border-neutral-150 shadow-sm font-semibold mt-[19px]">View More</button>
        </div>
      </div>
    </div>

    <!-- Property Card 2 (Duplicate for demo) -->
    <div class="bg-white rounded-lg shadow-md overflow-hidden">
      <img src="{% static 'images/bannerBefore.png' %}" alt="Property Image" class="w-full h-40 object-cover">
      <div class="p-4">
        <h2 class="text-lg font-bold text-gray-800">Bungalow Renovation</h2>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Created Date</p>
          <p class="text-sm text-gray-600">Jan 28, 2024</p>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Project Duration</p>
          <p class="text-sm text-gray-600">3 Months</p>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Home Owner</p>
          <div class="flex items-center">
            <img src="owner-image.jpg" alt="Owner Image" class="w-6 h-6 rounded-full">
            <p class="text-sm text-gray-600 ml-2">Olivia Rhye</p>
          </div>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Home Location</p>
          <p class="text-sm text-gray-600">35st California road, off 5th New York</p>
        </div>
        <div class="flex justify-between mt-2">
          <p class="text-sm text-gray-600">Quotation Status</p>
          <div class="flex gap-1 items-center bg-yellow-100 rounded-full px-2 py-1">
            <div class="w-[10px] h-[10px] rounded-full bg-yellow-500 "></div>
            <div class="text-sm text-yellow-500">Pending</div>
        </div>
        </div>
        <div class="text-center">
            <button class="inline-flex items-center w-[70%] md:w-[50%] justify-center p-3 rounded-3xl bg-black text-white border border-neutral-150 shadow-sm font-semibold mt-[19px]">View More</button>
        </div>
      </div>
    </div>
  </div>
    
</div>
{% endblock %}
{% block bottomNav %}
    {% include "user/bottom_nav_agent.html" %}
{% endblock bottomNav %} 
{% block extraScripts %}
    <script>
        function goBack() {
            history.back()
        }
    </script>
{% endblock extraScripts %}

templates/user/assignAgent.html
{% extends "user/base.html" %} 
{% load form_tags %}
{% load static %} 
{% include "user/bottom_navigation.html" %} 
{% block content %}
<div class="w-full">
    <!-- header -->
    <div class="w-full p-4 flex items-center mb-[18px]">
        <div onclick="goBack()">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 cursor-pointer">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
            </svg>
        </div>
        <h3 class="w-full text-xl mr-[48px] text-center text-gray-900 font-medium">Assign Agent</h3>
    </div>

    <div class="w-full p-4">
        <form method="POST" class="w-full mt-4 flex flex-col gap-4">
            {% csrf_token %}
            <div class="w-full">
                <label for="registration_ID" class="text-black font-medium text-sm">Agent License Number</label>
                <div class="border border-gray-300 rounded-3xl p-2 mt-1 h-[60px] pl-6">
                    <input
                        type="text"
                        name="registration_id"
                        id="registration_ID"
                        class="w-full rounded-3xl h-full focus:outline-none bg-transparent border-none focus:border-gray-500"
                        placeholder="Type here"
                    />
                </div>
            </div>


            <div class="flex w-full flex-col gap-4 items-center pt-[21px]">
                <button type="submit" class="inline-flex items-center w-[70%] md:w-[50%] justify-center p-3 rounded-3xl bg-black text-white border border-neutral-150 shadow-sm font-semibold">
                    Assign Agent
                </button>
                <a href = '{% url "main:home" %}' class="inline-flex items-center w-[70%] md:w-[50%] justify-center p-3 rounded-3xl bg-[#FFDEDE] text-red-500 border border-neutral-150 shadow-sm font-semibold">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %} 
{% block extraScripts %}
    <script>
        function goBack() {
            history.back()
        }
    </script>
{% endblock extraScripts %}

templates/user/bottom_nav.html
{% load static %}
<div class="w-full fixed bg-white bottom-0 border-t border-neutral-150 p-4 shadow-md z-20">
  {% with url_name=request.resolver_match.url_name %}
  <div class="flex items-center justify-between w-full">
    <a href="{% url 'main:home' %}" class="inline-flex flex-col gap-1 items-center">
      {% if url_name == 'home' %}
        <img src="{% static 'svgs/Home.svg' %}" alt="" class="" /> 
        <span class="text-primary font-medium text-xs">My Home</span> 
      {% else %}
        <img src="{% static 'svgs/Home-outline.svg' %}" alt="" class="" />
        <span class="text-gray-500 text-xs">My Home</span>
      {% endif %}
    </a>
    <a href="{% url 'profile:search_contractor' %}" class="inline-flex flex-col gap-1 items-center">
      {% if url_name == 'search_contractor' %}
        <img src="{% static 'svgs/search-selected.svg' %}" alt="" class="" />
        <span class="text-gray-500 text-xs font-medium text-primary">Search</span>
      {% else %}
        <img src="{% static 'svgs/search.svg' %}" alt="" class="" />
        <span class="text-gray-500 text-xs">Search</span>
      {% endif %}
      
    </a>
    
    {% if request.user.user_type == 'AG' %}
      <a href="{% url 'quotes:request-quotes' name='home_owner_slug' %}" class="inline-flex flex-col gap-1 items-center">       
      {% elif request.user.user_type == 'HO' %} 
      <a href="{% url 'quotes:request-quotes'%}" class="inline-flex flex-col gap-1 items-center">
    {% endif %}
      
      {% if url_name == 'home' %}
      {% else %}
      {% endif %}
      
      {% if url_name == 'request-quotes' %}
      <img src="{% static 'svgs/Upload-selected.svg' %}" alt="" class="" />
      <span class="text-gray-500 text-xs font-medium text-primary">Upload</span>
      {% else %}
      <img src="{% static 'svgs/Add-upload.svg' %}" alt="" class="" />
      <span class="text-gray-500 text-xs">Upload</span>
      {% endif %}
    </a>
    
    <a href="{% url 'profile:show-agent-message' %}" class="inline-flex flex-col gap-1 items-center">
      {% if url_name == 'home' %}
      {% else %}
      {% endif %}
      <img src="{% static 'svgs/Message.svg' %}" alt="" class="" />
      <span class="text-gray-500 text-xs">Messages</span>
    </a>
    <a href="{% url 'profile:show-agent-menu' %}" class="inline-flex flex-col gap-1 items-center">
      {% if url_name == 'edit-profile'%}
      <img src="{% static 'svgs/more-horizon-green.svg' %}" alt="" class="" />
      <span class="text-primary font-medium text-xs">Menu</span> 
      {% else %}
      <img src="{% static 'svgs/more-horizon.svg' %}" alt="" class="" />
      <span class="text-gray-500 text-xs">Menu</span>
      {% endif %}
    </a>
  </div>
  {% endwith %}
</div>

templates/user/bottom_nav_agent_r.html
{% load static %}
<div class="fixed bottom-0 w-full flex justify-between items-center bg-white h-16 border-t border-gray-200 shadow-lg ">
  {% with url_name=request.resolver_match.url_name %}
    <!-- home -->
    <a href="{% url 'main:home' %}" class="inline-flex flex-col gap-1 items-center">
      {% if url_name == 'home' %}
        <img src="{% static 'svgs/listing.svg' %}" alt="" class="" /> 
        <span class="text-primary text-xs">Listing</span> 
      {% else %}
        <img src="{% static 'svgs/listing-outline.svg' %}" alt="" class="" />
        <span class="text-gray-500 text-xs">Listing</span> 
      {% endif %}
    </a>

      <!-- Notifications Button -->
  <div class="flex flex-col items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-gray-600">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
      </svg>          
    <span class="text-xs text-gray-500">Notifications</span>
  </div>

    
   <!-- Upload Button -->
  <a href="{% url 'main:assigned-projects' %}" class="relative flex text-center flex-col mb-[4rem]">
    <button class="bg-green-500 text-white rounded-full p-8 shadow-lg">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.827 6.175A2.31 2.31 0 0 1 5.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 0 0-1.134-.175 2.31 2.31 0 0 1-1.64-1.055l-.822-1.316a2.192 2.192 0 0 0-1.736-1.039 48.774 48.774 0 0 0-5.232 0 2.192 2.192 0 0 0-1.736 1.039l-.821 1.316Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 12.75a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0ZM18.75 10.5h.008v.008h-.008V10.5Z" />
        </svg>
        
    </button>
    <span class="text-gray-500 text-xs">Upload</span>
  </a>

  <!-- listing/search -->
  <a href="{% url 'profile:search_contractor' %}" class="inline-flex flex-col gap-1 items-center">
    {% if url_name == 'search_contractor' %}
      <img src="{% static 'svgs/search-selected.svg' %}" alt="" class="" />
      <span class="text-gray-500 text-xs font-medium text-primary">Search</span>
    {% else %}
      <img src="{% static 'svgs/search.svg' %}" alt="" class="" />
      <span class="text-gray-500 text-xs">Search</span>
    {% endif %}     
  </a>

  
  {% comment %}    
    <!-- <a href="{% url 'profile:show-agent-message' %}" class="inline-flex flex-col gap-1 items-center">
      {% if url_name == 'home' %}
      {% else %}
      {% endif %}
      <i class="fa fa-bell" aria-hidden="true"></i>
      <span class="text-gray-500 text-xs">Messages</span>
    </a> -->
  {% endcomment %}

    
  {% comment %}
  <!-- <a href="{% url 'profile:show-agent-menu'  %}" class="inline-flex flex-col gap-1 items-center">
    {% if url_name == 'edit-profile'%}
    <i class="fa fa-bars" aria-hidden="true"></i>
    <span class="text-primary font-medium text-xs">Menu</span> 
    {% else %}
    <img src="{% static 'svgs/more-horizon.svg' %}" alt="" class="" />
    <span class="text-gray-500 text-xs">Menu</span>
    {% endif %}
  </a> -->     
  {% endcomment %}

  <!-- More Button -->
  <a href="{% url 'profile:show-agent-menu'  %}" class="flex flex-col items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-gray-600">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
      </svg>          
    <span class="text-xs text-gray-500">More</span>
  </a>
      
  {% endwith %}
</div>

templates/user/top-navigation.html
{% load static %}
<!-- the display modal -->
<div id="modal" class="relative hidden w-full">
    <div class="fixed inset-0 flex items-center justify-center z-50">
        <div class="fixed inset-0 bg-black/75"></div>
        <div class="bg-white w-[70%] md:w-[30%] rounded-lg z-50 absolute pb-3">
            <button id="close-modal-button" class="float-right cursor-pointer text-xl mb-2 ml-4">
                    <i class="fa fa-times mr-3 mt-3 text-red-700 hover:text-red-500" aria-hidden="true"></i>
                 </button>
            <div class="w-full flex flex-col items-center justify-center gap-9 mt-6 pb-3 ">
                <a href="{% url 'profile:edit-profile'%}" class="hover:bg-gray-300 py-3 text-center w-full rounded-lg">Edit profile <span><i class="fa fa-pencil ml-3" aria-hidden="true"></i>
                    </span></a>
                <a href="{% url 'logout' %}" class="hover:bg-gray-300 py-3 text-center w-full rounded-lg">Logout <span><i class="fa fa-sign-out ml-3" aria-hidden="true"></i>                    </span></a>
            </div>

        </div>
    </div>
</div>


<div class="w-full fixed top-0  shadow-sm bg-primary flex items-center py-4 z-10">
    <div id="profile-pic-navbar" class="w-[28px] h-full flex items-center absolute bottom-0 left-3 cursor-pointer ml-4">
        <img src="{% static 'svgs/avatar.svg' %}" alt="" class="w-full h-full object-contain" />
    </div>
    <div class="flex w-full items-center justify-center">
        <img src="{% static 'svgs/sproost-white.svg' %}" alt="" class="w-[7rem]" />
    </div>
</div>
<script>
    let profilePicnavbar = document.querySelector('#profile-pic-navbar')
    let closeModalButton = document.querySelector('#close-modal-button')
    let modal = document.querySelector('#modal')
    profilePicnavbar.onclick = () => {
        modal.style.display = "block"
    }
    closeModalButton.onclick = () => {
        modal.style.display = "none"
    }
</script>
</div>